# sdbus-c++ (DBus tray) + librsvg (SVG icons) + libudev (battery uevents):
# hyprbar links what Hyprland doesn't.
NAME       := hyprbar
PKGS_EXTRA := librsvg-2.0 libudev
LIBS_EXTRA := sdbus-c++ librsvg-2.0 libudev
include ../common/common.mk
