# sdbus-c++ (the notification daemon) + hyprgraphics (image decode):
# hyprnotify links what Hyprland doesn't.
NAME       := hyprnotify
PKGS_EXTRA := hyprgraphics
LIBS_EXTRA := sdbus-c++ hyprgraphics
include ../common/common.mk
